name: Feature Request
description: Template for new feature requests and development tasks
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Please provide a detailed overview of the task's goal, requirements, impact for higher level context. Can get into specifics in later descriptions.
      placeholder: Describe the feature or task in detail...
    validations:
      required: true

  - type: textarea
    id: frontend-components
    attributes:
      label: Relevant Components - Frontend
      description: List relevant files e.g.
      placeholder: |
        - `src/containers/SupplyProjectDetails.tsx` (/projects/[slug] for Supply roles)
    validations:
      required: false

  - type: textarea
    id: backend-components
    attributes:
      label: Relevant Components - Backend
      description: List relevant files e.g.
      placeholder: |
        - `explore/models.py` (Project object)
    validations:
      required: false

  - type: textarea
    id: frontend-changes
    attributes:
      label: Changes Required - Frontend
      description: Describe frontend changes required in a couple sentences.
      placeholder: Describe what needs to be built or modified on the frontend...
    validations:
      required: true

  - type: textarea
    id: backend-changes
    attributes:
      label: Changes Required - Backend
      description: Describe backend changes required in a couple sentences.
      placeholder: Describe what needs to be built or modified on the backend...
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: Completion & Testing Requirements
      description: Add a checklist of manual testing requirements
      placeholder: |
        - [ ] Add a checklist of manual testing requirements
    validations:
      required: true

  - type: textarea
    id: boilerplate
    attributes:
      label: Boilerplate
      description: Add any boilerplate or scaffolding code from sample components designed or prototyped (v0, claude, Figma, etc.)
      placeholder: Paste any relevant code snippets, designs, or prototypes here...
    validations:
      required: false

  - type: textarea
    id: screenshots-designs
    attributes:
      label: Screenshots & Designs
      description: Add design mocks or screenshots for visual context
      placeholder: Attach images or describe the visual requirements...
    validations:
      required: false
